### ISSUE TITLE
ソースコードについて

### ISSUE THREAD

**Issue by nakarin0528** [kazukios/daiyoseiroom#1]
初めまして！
Flutterの勉強中でkazukiosさんの[ブログ](https://techgamelife.net/2021/03/07/flutter-simple-question-app/)を見つけ，試し動かそうとしているのですが，Githubに挙げられているソースコードがおそらく途中のものなので，ブログで完成したソースコットをupしていただけないでしょうか？

よろしくお願いいたします！！

**Comment by kazukios** [comment]
初めまして。
コメントいただきありがとうございます。
pushしていないことに気づいていませんでした。。。

pushしたので、よろしければご覧になってみてください。

**Comment by nakarin0528** [comment]
ありがとうございます．
無事動きました！
